Bookz/config/routes.rb
Rails.application.routes.draw do

   root 'home#home'

  resources :books
  resources :authors


end

Bookz/app/models/author.rb
class Author < ActiveRecord::Base

  has_many :books

	
end

Bookz/app/models/book.rb
class Book < ActiveRecord::Base

	  belongs_to :author
	  
end

Bookz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Bookz/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(auth_params)

    if @author.save
      redirect_to root_path
    else
      render :new
    end
  end

private
  
  def auth_params
    params.require(:author).permit(:name)
  end

end

Bookz/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_strong_params)

    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

private
  
  def book_strong_params
    params.require(:book).permit(:title, :author_id, :year_published, :genre)
  end

end

Bookz/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    @books = Book.all
    @authors = Author.all    
  end

end

Bookz/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookz/app/views/authors/new.html.erb
<h1>Add Author</h1>

<!-- all the classes and the extra divs are only for bootstrap formatting -->
<!-- they have nothing to do with rails -->

<div style='width: 300px'>
<!-- because bootstrap makes inputs width:100% so if... -->
<!-- you don't put them in a div with a fixed width they... -->
<!-- span the whole page -->
  <%= form_for @author do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <%= f.submit 'Add Author', class: 'btn btn-warning' %>
  <% end %>
</div>

Bookz/app/views/authors/show.html.erb
<h1><%= @author.name %></h1>

<%= link_to 'Home', root_path %>

<h2>Books by <%= @author.name %></h2>

<table class='table'>
  <thead>
    <th>Title</th>
    <th>Author</th>
    <th>Genre</th>
    <th>Year</th>
  </thead>
  <tbody>
    <% @author.books.each do |b| %>
    <tr>
      <td><%= b.title %></td>
      <td><%= b.author.name %></td>
      <td><%= b.genre %></td>
      <td><%= b.year_published %></td>
    </tr>
    <% end %>
  </tbody>
</table>

Bookz/app/views/books/index.html.erb
<h1>Books</h1>

<a href="/books/new">Add a Book to the Library</a>

	<h2>Books in the Library</h2>
<table style="width:60%">

	
    <th>Title</th>
    <th>Genre</th> 
    <th>Year</th>
   
 </table>

	<% @books.each do |book| %>
<table style="width:60%">
  <tr>
  	<td><b> <%= book.title %> </b></td>
    <td> <%= book.genre %> </td>
    <td> <%= book.year_published %> </td> 

    <br>
  </tr>

 </table>

	<%end%>

Bookz/app/views/books/new.html.erb
<h1>Add A Book to the Library</h1>

<!-- all the classes and the extra divs are only for bootstrap formatting -->
<!-- they have nothing to do with rails -->

<div style='width: 400px'>
<!-- because bootstrap makes inputs width:100% so if... -->
<!-- you don't put them in a div with a fixed width they... -->
<!-- span the whole page -->

  <%= form_for @book do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
   

      <%= f.label :genre %>
      <%= f.text_field :genre, class: 'form-control' %>


      <%= f.label :year_published %>
      <%= f.number_field :year_published, class: 'form-control' %>



      <%= f.label :author_id %>
      <%= f.number_field :author_id, class: 'form-control' %>
 

    <%= f.submit 'Slide it on the shelf!', class: 'btn btn-warning' %>
  <% end %>
</div>

Bookz/app/views/home/home.html.erb
<h1>Bookz</h1>

<%= link_to 'Add a book', new_book_path %> | <%= link_to 'Add an author', new_author_path %>

<h2>All Books</h2>

<table class='table'>
  <thead>
    <th>Title</th>
    <th>Author</th>
    <th>Genre</th>
    <th>Year</th>
  </thead>
  <tbody>
    <% @books.each do |b| %>
    <tr>
      <td><%= b.title %></td>
      <td><%= b.author.name %></td>
      <td><%= b.genre %></td>
      <td><%= b.year_published %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>All Authors</h2>

<ul>
  <% @authors.each do |a| %>
    <li><%= link_to "#{a.id} | #{a.name}", author_path(a) %></li>
  <% end %>
</ul>